# Setup
title: 'mhut.ch'
tagline: 'cloud residence'
description: "Mikayla Hutchinson's home on the web"

url:              https://mhut.ch

author:
  name:           'Mikayla Hutchinson'
  url:            https://twitter.com/mjhutchinson

permalink: journal/:year/:month/:day/:title

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true

sidebar_home_link:  true
sidebar_blog_link:  '/journal'

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  permalinks:
    year: '/journal/:year/'
    month: '/journal/:year/:month/'
    tag: '/journal/tags/:name/'
  layouts:
    year: archive-year
    month: archive-month
    tag: archive-tags

# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins:
  - jekyll-paginate-v2
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-archives