# Setup
title: 'mhut.ch'
description: "Mikayla Hutchinson's home on the web"

url: https://mhut.ch

google_tag_container: GTM-M9VCVCX

author:
  name: Mikayla Hutchinson
  twitter: mjhutchinson

twitter:
  username: mjhutchinson
  card: summary

linkedin:
  username: mjhutchinson

social:
  name: Mikayla Hutchinson
  links:
    - https://twitter.com/mjhutchinson
    - https://www.facebook.com/mhutch
    - https://www.linkedin.com/in/mjhutchinson
    - https://plus.google.com/+mjhutchinson
    - https://github.com/mhutch
    - https://keybase.io/mhutch

disqus:
  shortname: mhutch

permalink: journal/:year/:month/:day/:title

excerpt_separator: "<!--break-->"

include: ["_pages", "_redirects"]
keep_files: [files]

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true

sidebar_home_link:  true
sidebar_blog_link:  '/journal/'

collections_dir: content
collections:
- talks

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      layout: 'journal'

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  permalinks:
    year: '/journal/:year/'
    month: '/journal/:year/:month/'
    tag: '/tags/:name/'
  layouts:
    year: archive-year
    month: archive-month
    tag: archive-tags

# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins:
  - jekyll-paginate-v2
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-archives
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll-seo-tag

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - Rakefile